name: build
on:
  - push
  - pull_request

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

env:
  TYPE: ${{ endsWith(github.ref_name, 'main') && 'release' || (endsWith(github.ref_name, 'beta') && 'beta' || 'dev') }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' && github.ref_name != 'main' && github.ref_name != 'beta' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@v4

      - name: "☕ Setup Jdk 21"
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          cache-dependency-path: |
            versions/*.properties
            *.properties
            *.gradle.kts
          java-version: 21
          check-latest: true
          distribution: 'temurin'

      - name: "Patch completed languages"
        run: ./scripts/patch-completed-langs.sh
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: "🛂 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: "🔓 Adjust the release permissions"
        run: chmod a+x ./scripts/release.sh && chmod +x ./gradlew

      - name: "🧵 Install semantic release"
        run: npm i --location=global @meza/mezas-conventional-changelog semantic-release semantic-release-discord-notifier conventional-changelog-conventionalcommits @semantic-release/github @semantic-release/changelog @semantic-release/exec semantic-release-export-data semantic-release-discord

      - name: "🔢 Determine version"
        run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: "ℹ️ Needs Release?"
        run: echo "Needs release published? ${{ steps.get-next-version.outputs.new-release-published == 'true' }}"

      - name: "🔨 Data Gen"
        run: |
          chmod +x ./scripts/datagen.sh
          ./scripts/datagen.sh

      - name: "🏗️ Build & Release to GitHub"
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DO_PUBLISH: steps.get-next-version.outputs.new-release-published
          MODRINTH_ID: ${{ vars.MODRINTH_ID }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_ID: ${{ vars.CURSEFORGE_ID }}
          CURSEFORGE_SLUG: ${{ vars.CURSEFORGE_SLUG }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: npx semantic-release

      - name: "🧪 Run Dev Build"
        if: ${{ steps.get-next-version.outputs.new-release-published != 'true' }}
        run: ./gradlew chiseledGameTest chiseledBuildAndCollect --stacktrace

      - name: "🕵️‍♂️ Collect jars"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            build/reports/**/*

